# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-up-and-running-state-nm-0411"
    dynamodb_table = "terraform-up-and-running-locks"
    encrypt        = true
    key            = "s3copy/terraform.tfstate"
    region         = "us-east-1"
  }
}
